#!/usr/bin/env bash


usage() {
    echo "Usage:"
    echo "  psstat <pid>"
}


check_args() {
    if [ $# -ne 1 ]; then
        usage
        exit 1
    fi

    PID=$1

    if [[ !($PID =~ ^[0-9]+$) ]]; then
        usage
        exit 1
    fi

    if [ ! -d "/proc/$PID" ]; then
        echo "Error: Process with PID $PID does not exist"
        exit 1
    fi
}


parse_stat() {
    local stat_info=$(cat /proc/$PID/stat 2>/dev/null)
    if [ $? -ne 0 ]; then
        echo "Error: Cannot read /proc/$PID/stat"
        exit 1
    fi
    
    name=$(echo $stat_info | cut -d ' ' -f 2 | tr -d '()')
    state=$(echo $stat_info | cut -d ' ' -f 3)
    ppid=$(echo $stat_info | cut -d ' ' -f 4)
    utime=$(echo $stat_info | cut -d ' ' -f 14)
    stime=$(echo $stat_info | cut -d ' ' -f 15)
    num_threads=$(echo $stat_info | cut -d ' ' -f 20)
}


parse_status() {
    if [ ! -f "/proc/$PID/status" ]; then
        echo "Error: Cannot read /proc/$PID/status"
        exit 1
    fi

    voluntary_ctxt_switches=$(grep -w 'voluntary_ctxt_switches' /proc/$PID/status | cut -f 2)
    nonvoluntary_ctxt_switches=$(grep -w 'nonvoluntary_ctxt_switches' /proc/$PID/status | cut -f 2)
    vm_rss_kb=$(grep -w 'VmRSS' /proc/$PID/status | cut -f 2 | tr -d -c [:digit:])
    rss_anon_kb=$(grep -w 'RssAnon' /proc/$PID/status | cut -f 2 | tr -d -c [:digit:])
    rss_file_kb=$(grep -w 'RssFile' /proc/$PID/status | cut -f 2 | tr -d -c [:digit:])
}


parse_io() {
    if [ ! -f "/proc/$PID/io" ]; then
        echo "Warning: Cannot read /proc/$PID/io"
        return
    fi
    
    read_bytes=$(grep -w 'read_bytes' /proc/$PID/io | cut -d ' ' -f 2)
    write_bytes=$(grep -w 'write_bytes' /proc/$PID/io | cut -d ' ' -f 2)
}


calculate_cpu_time() {
    # Get system HZ (clock ticks per second)
    local HZ=$(getconf CLK_TCK 2>/dev/null)
    if [ -z "$HZ" ] || [ "$HZ" -eq 0 ]; then
        HZ=100  # Default fallback
    fi
    
    cpu_time_sec=$(echo "scale=2; ($utime + $stime) / $HZ" | bc 2>/dev/null)
    if [ -z "$cpu_time_sec" ]; then
        cpu_time_sec="N/A"
    else
        cpu_time_sec="${cpu_time_sec} sec"
    fi
}


format_kb() {
    local kb=$1
    if [ -z "$kb" ]; then
        echo "N/A"
    elif [ $kb -ge 1024 ]; then
        echo "$(($kb/1024)) MiB ($kb KiB)"
    else
        echo "$kb KiB"
    fi
}


format_bytes() {
    local bytes=$1
    if [ -z "$bytes" ]; then
        echo "N/A"
    elif [ $bytes -ge 1048576 ]; then
        echo "$(($bytes/1048576)) MiB ($(($bytes/1024)) KiB)"
    elif [ $bytes -ge 1024 ]; then
        echo "$(($bytes/1024)) KiB"
    else
        echo "$bytes bytes"
    fi
}

show_info() {
    echo "=== Process $PID Statistics ==="
    echo -e "Name:\t\t\t$name"
    echo -e "State:\t\t\t$state"
    echo -e "CPU time:\t\t$cpu_time_sec"
    echo -e "PPid:\t\t\t$ppid"
    echo -e "utime:\t\t\t$utime"
    echo -e "stime:\t\t\t$stime"
    echo -e "Threads:\t\t$num_threads"
    echo -e "Voluntary switches:\t$voluntary_ctxt_switches"
    echo -e "Nonvoluntary switches:\t$nonvoluntary_ctxt_switches"
    echo -e "VmRSS:\t\t\t$(format_kb "$vm_rss_kb")"
    echo -e "RssAnon:\t\t$(format_kb "$rss_anon_kb")"
    echo -e "RssFile:\t\t$(format_kb "$rss_file_kb")"
    echo -e "Read bytes:\t\t$(format_bytes "$read_bytes")"
    echo -e "Write bytes:\t\t$(format_bytes "$write_bytes")"
}


main() {
    check_args "$@"
    
    parse_stat
    parse_status
    parse_io
    parse_smaps
    calculate_cpu_time

    show_info
}


main "$@"
